In [1]:
import numpy as np
import pandas as pd

In [31]:
# read-in world population growth data
un_data = pd.read_csv("API_SP.POP.GROW_DS2_en_csv_v2_9946255.csv",skiprows=3)
#un_data = un_data.set_index("Country Name")
display(un_data)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,Population growth (annual %),SP.POP.GROW,3.148037,2.238144,1.409622,0.832453,0.592649,0.573468,...,0.098616,0.212680,0.376985,0.512145,0.592914,0.587492,0.524658,0.459929,NaN,NaN
1,Afghanistan,AFG,Population growth (annual %),SP.POP.GROW,1.816077,1.876528,1.934999,1.992521,2.049423,2.105369,...,2.569114,2.812617,3.095119,3.272703,3.315224,3.183201,2.943234,2.689163,NaN,NaN
2,Angola,AGO,Population growth (annual %),SP.POP.GROW,1.903517,1.927754,1.945774,1.930693,1.870296,1.788799,...,3.566821,3.570099,3.570352,3.559496,3.531824,3.485413,3.428021,3.367572,NaN,NaN
3,Albania,ALB,Population growth (annual %),SP.POP.GROW,3.015423,3.120855,3.056731,2.953749,2.880686,2.754021,...,-0.673894,-0.496462,-0.269017,-0.165151,-0.183211,-0.207047,-0.291206,-0.159880,NaN,NaN
4,Andorra,AND,Population growth (annual %),SP.POP.GROW,7.050663,6.941532,6.692697,6.559522,6.241511,5.998800,...,0.714106,-0.015393,-0.829969,-1.588653,-2.013314,-1.956178,-1.537836,-0.944017,NaN,NaN
5,Arab World,ARB,Population growth (annual %),SP.POP.GROW,NaN,2.760881,2.775328,2.793528,2.817245,2.842976,...,2.448201,2.402393,2.352527,2.305073,2.248844,2.185197,2.118210,2.045601,NaN,NaN
6,United Arab Emirates,ARE,Population growth (annual %),SP.POP.GROW,5.859584,8.723625,10.681181,11.012721,9.824817,8.196603,...,10.615444,7.587098,4.743700,2.594796,1.181805,0.714763,0.915608,1.251759,NaN,NaN
7,Argentina,ARG,Population growth (annual %),SP.POP.GROW,1.630874,1.606889,1.584309,1.557532,1.524221,1.489544,...,1.027377,1.035037,1.044860,1.050376,1.047277,1.032709,1.009855,0.984742,NaN,NaN
8,Armenia,ARM,Population growth (annual %),SP.POP.GROW,3.596386,3.531702,3.444264,3.330247,3.193727,3.044919,...,-0.677479,-0.391024,-0.060144,0.220269,0.401252,0.438332,0.368528,0.269302,NaN,NaN
9,American Samoa,ASM,Population growth (annual %),SP.POP.GROW,1.403903,2.335966,3.033668,3.558598,3.661243,3.557431,...,-1.418038,-1.054862,-0.571394,-0.162822,0.139320,0.234776,0.180222,0.111575,NaN,NaN
10,Antigua and Barbuda,ATG,Population growth (annual %),SP.POP.GROW,1.121208,1.444191,1.765458,1.992477,2.088042,2.089765,...,1.185659,1.147472,1.111473,1.099255,1.076058,1.068648,1.054346,1.035422,NaN,NaN
11,Australia,AUS,Population growth (annual %),SP.POP.GROW,2.266912,1.989740,2.440639,1.917816,1.962354,1.959717,...,2.061045,1.555490,1.389527,1.785445,1.758338,1.535879,1.464060,1.498210,NaN,NaN
12,Austria,AUT,Population growth (annual %),SP.POP.GROW,0.510799,0.548472,0.612896,0.642363,0.666548,0.649730,...,0.261953,0.240394,0.337081,0.455937,0.584104,0.730867,1.066623,1.132221,NaN,NaN
13,Azerbaijan,AZE,Population growth (annual %),SP.POP.GROW,3.316315,3.405043,3.441193,3.386928,3.227913,3.004238,...,2.076148,1.189788,1.303001,1.328764,1.293447,1.248209,1.191210,1.117857,NaN,NaN
14,Burundi,BDI,Population growth (annual %),SP.POP.GROW,1.945067,1.904152,1.883881,1.925484,2.044533,2.201433,...,3.314621,3.221183,3.106046,3.008436,2.965096,2.992265,3.061103,3.135333,NaN,NaN
15,Belgium,BEL,Population growth (annual %),SP.POP.GROW,0.657711,0.332206,0.398055,0.747607,0.946478,0.908137,...,0.804600,0.913639,1.386849,0.726032,0.489184,0.234371,0.579446,0.568532,NaN,NaN
16,Benin,BEN,Population growth (annual %),SP.POP.GROW,1.303687,1.398495,1.490499,1.584058,1.680971,1.778052,...,2.809337,2.806109,2.803422,2.797040,2.790253,2.782287,2.772978,2.763534,NaN,NaN
17,Burkina Faso,BFA,Population growth (annual %),SP.POP.GROW,1.359523,1.342943,1.334299,1.351523,1.403618,1.479135,...,3.026450,3.019245,3.008938,2.997255,2.981483,2.961978,2.939690,2.915614,NaN,NaN
18,Bangladesh,BGD,Population growth (annual %),SP.POP.GROW,2.845730,2.849193,2.857068,2.901407,2.994149,3.101175,...,1.101990,1.119888,1.151949,1.172435,1.177319,1.157188,1.120144,1.080165,NaN,NaN
19,Bulgaria,BGR,Population growth (annual %),SP.POP.GROW,0.952937,0.958156,0.875259,0.810378,0.816094,0.731911,...,-0.644281,-0.658275,-0.641229,-0.579221,-0.559647,-0.568389,-0.638069,-0.701382,NaN,NaN
20,Bahrain,BHR,Population growth (annual %),SP.POP.GROW,3.540426,3.310416,3.079079,2.844614,2.629872,2.454230,...,6.128062,4.603905,2.970052,1.702435,1.161799,1.582802,2.618665,3.812797,NaN,NaN
21,"Bahamas, The",BHS,Population growth (annual %),SP.POP.GROW,4.790266,4.969059,5.060544,5.032944,4.877782,4.644454,...,1.756895,1.670040,1.577157,1.481464,1.388290,1.298133,1.214308,1.129473,NaN,NaN
22,Bosnia and Herzegovina,BIH,Population growth (annual %),SP.POP.GROW,1.892666,1.932249,1.946032,1.900808,1.781252,1.615087,...,-0.453733,-0.655463,-0.896490,-1.108493,-1.191240,-1.087641,-0.845996,-0.542908,NaN,NaN
23,Belarus,BLR,Population growth (annual %),SP.POP.GROW,0.977388,0.889131,0.971087,1.016188,1.025770,1.001233,...,-0.222961,-0.170361,-0.183624,-0.091637,0.015869,0.089903,0.159301,0.125511,NaN,NaN
24,Belize,BLZ,Population growth (annual %),SP.POP.GROW,2.835710,2.826169,2.791625,2.814692,2.858982,2.916244,...,2.504267,2.416657,2.330775,2.255413,2.197239,2.159380,2.136282,2.111220,NaN,NaN
25,Bermuda,BMU,Population growth (annual %),SP.POP.GROW,1.360606,2.477477,2.417582,2.360515,2.515723,2.453988,...,0.556126,-0.780060,-0.859898,0.362431,0.313281,0.212304,0.170405,0.193103,NaN,NaN
26,Bolivia,BOL,Population growth (annual %),SP.POP.GROW,1.899198,1.913748,1.927848,1.942861,1.960071,1.978196,...,1.641612,1.621157,1.601318,1.581549,1.562684,1.544652,1.527225,1.510047,NaN,NaN
27,Brazil,BRA,Population growth (annual %),SP.POP.GROW,2.895857,2.926272,2.944039,2.935051,2.893086,2.829378,...,0.988454,0.970296,0.956013,0.938920,0.917023,0.887563,0.852799,0.817556,NaN,NaN
28,Barbados,BRB,Population growth (annual %),SP.POP.GROW,0.255806,0.319487,0.391157,0.429455,0.410140,0.351974,...,0.414187,0.393880,0.368460,0.350062,0.327605,0.309599,0.293163,0.273711,NaN,NaN
29,Brunei Darussalam,BRN,Population growth (annual %),SP.POP.GROW,4.793482,4.603391,4.477883,4.435656,4.464131,4.571557,...,1.184773,1.266145,1.367383,1.445044,1.481906,1.465124,1.408049,1.345029,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,Population growth (annual %),SP.POP.GROW,NaN,2.818179,2.825262,2.817722,2.792543,2.755422,...,1.266713,1.242578,1.218160,1.194523,1.168787,1.140712,1.110923,1.080345,NaN,NaN
235,Timor-Leste,TLS,Population growth (annual %),SP.POP.GROW,1.720283,1.763536,1.803833,1.843901,1.883992,1.921231,...,1.282060,1.596137,1.957303,2.205848,2.358462,2.373567,2.295569,2.207092,NaN,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,Population growth (annual %),SP.POP.GROW,NaN,2.678631,2.676427,2.682782,2.700735,2.724247,...,1.829205,1.836704,1.846016,1.850813,1.837212,1.800939,1.750039,1.691423,NaN,NaN
237,Tonga,TON,Population growth (annual %),SP.POP.GROW,2.845245,3.421265,3.868056,4.060766,3.910645,3.565965,...,0.579841,0.513140,0.421630,0.356993,0.358572,0.430108,0.548680,0.710120,NaN,NaN
238,South Asia (IDA & IBRD),TSA,Population growth (annual %),SP.POP.GROW,NaN,2.108723,2.144198,2.175983,2.203970,2.228436,...,1.470932,1.439535,1.409844,1.379665,1.353617,1.326264,1.298149,1.272433,NaN,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,Population growth (annual %),SP.POP.GROW,NaN,2.372225,2.409552,2.443646,2.473750,2.501111,...,2.766432,2.772365,2.775840,2.777187,2.771639,2.758781,2.740719,2.720355,NaN,NaN
240,Trinidad and Tobago,TTO,Population growth (annual %),SP.POP.GROW,2.263549,1.970027,1.680244,1.415578,1.192323,1.007007,...,0.473723,0.489261,0.502313,0.508151,0.495198,0.462124,0.412513,0.357424,NaN,NaN
241,Tunisia,TUN,Population growth (annual %),SP.POP.GROW,1.273002,1.418701,1.573834,1.716618,1.832820,1.926503,...,1.094158,1.116147,1.135788,1.156704,1.167893,1.167513,1.157614,1.142911,NaN,NaN
242,Turkey,TUR,Population growth (annual %),SP.POP.GROW,2.445584,2.425762,2.407683,2.393834,2.385335,2.380924,...,1.268402,1.375056,1.485643,1.568376,1.619467,1.627194,1.598009,1.573012,NaN,NaN
243,Tuvalu,TUV,Population growth (annual %),SP.POP.GROW,2.018933,2.299696,2.263650,2.305355,2.208530,1.940945,...,0.972049,0.858293,0.916874,0.908544,0.872638,0.819262,0.848971,0.868862,NaN,NaN
244,Tanzania,TZA,Population growth (annual %),SP.POP.GROW,2.894983,2.923647,2.949385,2.969345,2.982472,2.992332,...,3.171010,3.160941,3.143889,3.129141,3.116185,3.107572,3.100829,3.092454,NaN,NaN
245,Uganda,UGA,Population growth (annual %),SP.POP.GROW,3.037759,3.166940,3.278797,3.358024,3.397666,3.403791,...,3.439418,3.429003,3.415883,3.398480,3.376766,3.350650,3.321556,3.290872,NaN,NaN
246,Ukraine,UKR,Population growth (annual %),SP.POP.GROW,1.254451,1.261255,1.255486,1.218682,1.141518,1.038489,...,-0.443932,-0.397285,-0.359480,-0.247099,-0.227705,-0.479616,-0.260806,-0.331381,NaN,NaN
247,Upper middle income,UMC,Population growth (annual %),SP.POP.GROW,NaN,0.390332,1.449802,2.384555,2.300796,2.324726,...,0.739477,0.733982,0.741677,0.767561,0.776514,0.775232,0.756839,0.754159,NaN,NaN
248,Uruguay,URY,Population growth (annual %),SP.POP.GROW,1.333812,1.293043,1.244206,1.192681,1.141825,1.087600,...,0.355429,0.346140,0.331626,0.328881,0.330004,0.338072,0.350484,0.362269,NaN,NaN
249,United States,USA,Population growth (annual %),SP.POP.GROW,1.701993,1.657730,1.537997,1.439165,1.389046,1.250172,...,0.876651,0.836422,0.745614,0.746420,0.700262,0.743124,0.729732,0.692801,NaN,NaN
250,Uzbekistan,UZB,Population growth (annual %),SP.POP.GROW,3.280758,3.311496,3.346521,3.401222,3.479350,3.559889,...,1.687341,2.822850,2.684016,1.472100,1.561904,1.686900,1.744258,1.738849,NaN,NaN
251,St. Vincent and the Grenadines,VCT,Population growth (annual %),SP.POP.GROW,1.657913,1.463013,1.287000,1.148346,1.065977,1.053571,...,0.080579,0.056733,0.023782,-0.011890,-0.007318,0.033840,0.089575,0.171613,NaN,NaN
252,"Venezuela, RB",VEN,Population growth (annual %),SP.POP.GROW,3.750555,3.791735,3.813339,3.792220,3.718496,3.610993,...,1.571087,1.529865,1.488310,1.448190,1.410957,1.377539,1.346708,1.317057,NaN,NaN
253,British Virgin Islands,VGB,Population growth (annual %),SP.POP.GROW,1.265285,1.507318,1.738329,1.838858,2.049372,2.144455,...,3.239414,2.895621,2.456359,2.155730,1.900518,1.814387,1.758810,1.803452,NaN,NaN
254,Virgin Islands (U.S.),VIR,Population growth (annual %),SP.POP.GROW,4.725288,5.390526,2.020271,12.851885,2.481517,6.407886,...,0.005535,-0.043365,-0.060928,-0.093310,-0.135963,-0.148198,-0.161415,-0.185856,NaN,NaN
255,Vietnam,VNM,Population growth (annual %),SP.POP.GROW,3.020929,3.003488,2.977189,2.948605,2.921171,2.891446,...,0.984217,1.030588,1.083858,1.128752,1.149610,1.137999,1.103247,1.060392,NaN,NaN
256,Vanuatu,VUT,Population growth (annual %),SP.POP.GROW,3.036259,3.112791,3.138341,3.130064,3.050309,2.947898,...,2.387617,2.359448,2.332350,2.294545,2.260062,2.229815,2.198185,2.167915,NaN,NaN
257,World,WLD,Population growth (annual %),SP.POP.GROW,NaN,1.359037,1.729087,2.087843,2.057572,2.059444,...,1.230668,1.216246,1.184470,1.205276,1.204717,1.199008,1.184693,1.177832,NaN,NaN
258,Samoa,WSM,Population growth (annual %),SP.POP.GROW,3.052203,3.146592,3.220013,3.206577,3.123157,2.966411,...,0.705850,0.743338,0.781024,0.811449,0.822742,0.800428,0.761047,0.702526,NaN,NaN
259,Kosovo,XKX,Population growth (annual %),SP.POP.GROW,2.026736,1.986474,2.857337,2.777956,2.702867,2.631731,...,0.803172,0.803249,0.859067,0.789727,1.041533,-0.126169,-1.103886,0.796024,NaN,NaN
260,"Yemen, Rep.",YEM,Population growth (annual %),SP.POP.GROW,1.668753,1.694071,1.720650,1.746020,1.770406,1.793275,...,2.729135,2.713034,2.697367,2.676050,2.639892,2.585905,2.520254,2.451502,NaN,NaN
261,South Africa,ZAF,Population growth (annual %),SP.POP.GROW,2.593165,2.622255,2.648309,2.668551,2.681810,2.690160,...,1.102147,1.197113,1.307414,1.395966,1.440907,1.425925,1.368770,1.301374,NaN,NaN
262,Zambia,ZMB,Population growth (annual %),SP.POP.GROW,3.012665,3.085655,3.144761,3.175555,3.171658,3.149049,...,2.817933,2.883152,2.950426,3.005133,3.036918,3.040211,3.024123,3.002816,NaN,NaN
263,Zimbabwe,ZWE,Population growth (annual %),SP.POP.GROW,3.199877,3.239584,3.269926,3.279540,3.263725,3.234102,...,1.842497,1.976756,2.109672,2.228306,2.309366,2.344799,2.345643,2.336070,NaN,NaN

In [32]:
# isolate china's population growth (1960-2016)
china_popg = un_data.loc[un_data["Country Name"] == "China"]
china_popg.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
38,China,CHN,Population growth (annual %),SP.POP.GROW,1.832868,-1.015528,0.820456,2.457647,2.320683,2.381368,...,0.497381,0.48296,0.47915,0.487231,0.49371,0.506312,0.508137,0.541479,NaN,NaN

In [35]:
pop_a = china_popg.iloc[:,4:23]
display(pop_a)

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978
38,1.832868,-1.015528,0.820456,2.457647,2.320683,2.381368,2.787332,2.570698,2.610903,2.740002,2.761676,2.746916,2.457357,2.283395,2.065955,1.766392,1.547338,1.362779,1.338182

In [37]:
pop_b = china_popg.iloc[:,23:len(china_popg.columns)-2]
display(pop_b)

,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
38,1.333928,1.254221,1.280952,1.472675,1.44495,1.312069,1.361699,1.487399,1.603605,1.610071,...,0.522272,0.512387,0.497381,0.48296,0.47915,0.487231,0.49371,0.506312,0.508137,0.541479

In [38]:
# read-in GDP data
gdp_data = pd.read_csv("API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_9944801.csv",skiprows=3)
display(gdp_data)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.653502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,21.020649,8.433290,6.113685,14.434741,3.900575,2.690522,1.310040,2.366712,NaN,NaN
2,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.412870,3.407655,3.918597,5.155441,6.813586,4.804473,3.006981,-0.665353,NaN,NaN
3,Albania,ALB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.352610,3.710058,2.550161,1.419968,1.000755,1.774369,2.226581,3.369989,NaN,NaN
4,Andorra,AND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.690654,-5.358826,-4.646543,-1.615218,0.351645,2.277683,0.842204,1.232243,NaN,NaN
5,Arab World,ARB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.429767,4.775796,3.550247,5.172594,3.678027,2.919966,3.404067,3.221987,NaN,NaN
6,United Arab Emirates,ARE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.242922,1.635449,6.358920,5.104679,5.789906,3.284926,3.828867,3.036460,NaN,NaN
7,Argentina,ARG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,5.427843,-0.852022,-5.308197,10.130298,10.569433,...,-5.918525,10.125398,6.003952,-1.026420,2.405324,-2.512615,2.647271,-2.245344,NaN,NaN
8,Armenia,ARM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-14.149989,2.200000,4.700000,7.200000,3.300000,3.600000,3.200000,0.200000,NaN,NaN
9,American Samoa,ASM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.237288,0.442478,0.293686,-4.392387,-2.756508,0.944882,1.248050,-2.619414,NaN,NaN
10,Antigua and Barbuda,ATG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-12.107536,-7.200024,-2.079127,3.506609,-0.103939,5.101940,4.060219,5.342479,NaN,NaN
11,Australia,AUS,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,2.474965,1.326665,6.212971,6.975490,5.978494,...,1.811957,2.005880,2.372821,3.634250,2.569856,2.609457,2.421611,2.765773,NaN,NaN
12,Austria,AUT,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,5.537979,2.648675,4.138268,6.124354,3.480175,...,-3.799075,1.928673,2.922798,0.680444,0.025504,0.828734,1.091854,1.450915,NaN,NaN
13,Azerbaijan,AZE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,9.410654,4.854339,0.065923,2.200000,5.796678,2.000000,1.100000,-3.100000,NaN,NaN
14,Burundi,BDI,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,-13.746135,9.063158,4.135407,6.273038,3.967226,...,3.468425,3.785903,4.191626,4.019366,4.594054,4.660918,-3.921143,-0.570434,NaN,NaN
15,Belgium,BEL,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.978423,5.212004,4.351584,6.956685,3.560660,...,-2.253175,2.744213,1.798303,0.234797,0.200650,1.351434,1.404495,1.466005,NaN,NaN
16,Benin,BEN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.141280,-3.426410,4.730028,6.650759,5.293863,...,2.319227,2.116850,2.962750,4.810283,7.193097,6.357521,2.094458,3.981288,NaN,NaN
17,Burkina Faso,BFA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.043928,6.128799,-1.268016,2.282819,3.764545,...,2.962014,5.373373,6.626865,6.452699,5.792589,4.326837,3.894545,5.915798,NaN,NaN
18,Bangladesh,BGD,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.058161,5.453031,-0.455894,10.952789,1.606258,...,5.045125,5.571802,6.464384,6.521435,6.013596,6.061093,6.552633,7.113489,NaN,NaN
19,Bulgaria,BGR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.586146,1.324027,1.915018,0.030944,0.862093,1.328850,3.617443,3.941070,NaN,NaN
20,Bahrain,BHR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.539772,4.334407,1.983823,3.732252,5.416504,4.349842,2.861968,NaN,NaN,NaN
21,"Bahamas, The",BHS,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,10.667097,10.451972,10.524055,10.501567,10.425596,...,-4.180920,1.547005,0.611979,3.080109,-0.567138,-1.242999,-3.071092,0.165623,NaN,NaN
22,Bosnia and Herzegovina,BIH,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.989663,0.867983,0.955705,-0.824089,2.350840,1.149714,3.073772,3.056220,NaN,NaN
23,Belarus,BLR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.199995,7.793698,5.543711,1.731393,1.023985,1.723086,-3.829569,-2.649038,NaN,NaN
24,Belize,BLZ,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.892277,4.892652,4.956434,4.999880,4.930541,...,0.713118,3.324442,2.103951,3.824749,1.314079,3.501786,2.871935,-0.594298,NaN,NaN
25,Bermuda,BMU,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.680000,4.470000,1.070000,11.110000,4.760000,...,-5.284177,-2.094114,-3.339494,-4.834540,-2.511154,NaN,NaN,NaN,NaN,NaN
26,Bolivia,BOL,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,2.079984,5.570225,6.420702,4.794560,5.625018,...,3.357001,4.126723,5.204093,5.122275,6.796012,5.460570,4.857188,4.263919,NaN,NaN
27,Brazil,BRA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,10.275912,5.216059,0.874673,3.485582,3.053488,...,-0.125873,7.528224,3.974425,1.921150,3.004865,0.503962,-3.769253,-3.594739,NaN,NaN
28,Barbados,BRB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.041024,0.264913,0.455539,0.281154,0.009044,0.018086,0.904159,2.043011,NaN,NaN
29,Brunei Darussalam,BRN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.764536,2.598966,3.745318,0.912842,-2.126029,-2.349747,-0.566815,-2.465515,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.541435,4.711373,2.411139,7.429333,5.088047,...,-1.760104,6.014590,4.555130,2.929086,2.856867,0.925134,-0.206670,-0.654538,NaN,NaN
235,Timor-Leste,TLS,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,13.000978,10.121107,7.934014,5.021834,2.633403,4.186361,4.082955,5.666252,NaN,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.519562,5.251352,-1.013031,0.099308,2.282749,3.210554,1.353971,7.579924,NaN,NaN
237,Tonga,TON,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.290613,3.585657,2.785146,0.890323,-3.120604,2.072607,3.711847,3.379474,NaN,NaN
238,South Asia (IDA & IBRD),TSA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.119448,3.326567,5.358464,7.699577,-0.951869,...,7.609017,9.055344,6.313792,5.518073,6.073084,7.068094,7.483023,6.823352,NaN,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.501185,5.847018,6.308077,5.403583,4.981966,...,2.881796,5.398274,4.361375,3.776558,4.843745,4.639630,3.043379,1.239104,NaN,NaN
240,Trinidad and Tobago,TTO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,14.037071,2.742463,5.604597,7.630500,0.693850,...,-4.390592,3.323331,-0.294354,1.293979,2.653918,-0.575925,-0.578522,-2.268341,NaN,NaN
241,Tunisia,TUN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.043449,3.510609,-1.917178,3.997666,2.874754,2.823160,1.149408,1.169769,NaN,NaN
242,Turkey,TUR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.156069,5.571429,9.066306,5.459057,2.823530,...,-4.704466,8.487372,11.113496,4.789940,8.491309,5.166691,6.085887,3.183832,NaN,NaN
243,Tuvalu,TUV,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.432851,-2.729428,8.453324,0.174458,1.298188,2.235866,2.642147,2.743245,NaN,NaN
244,Tanzania,TZA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.382346,6.358886,7.904508,5.141014,7.263060,6.965133,6.959374,6.970605,NaN,NaN
245,Uganda,UGA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.801517,5.637612,9.391655,3.837456,3.586906,5.106307,5.187860,4.656576,NaN,NaN
246,Ukraine,UKR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-14.800000,4.200000,5.465532,0.238681,-0.026730,-6.552619,-9.772974,2.307602,NaN,NaN
247,Upper middle income,UMC,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.820847,3.865553,4.699404,8.361312,7.017803,...,1.502520,7.530194,6.334423,4.892417,5.031404,4.072951,3.337471,3.717412,NaN,NaN
248,Uruguay,URY,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,2.493038,-1.574549,0.170459,2.440521,1.045604,...,4.243494,7.803410,5.162133,3.538179,4.637539,3.238791,0.370741,1.453431,NaN,NaN
249,United States,USA,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,2.300000,6.100000,4.400000,5.800000,6.400000,...,-2.775530,2.531921,1.601455,2.224031,1.677332,2.569194,2.861587,1.485279,NaN,NaN
250,Uzbekistan,UZB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,8.100000,8.500000,8.300000,8.200000,8.000000,7.792522,8.000000,7.800000,NaN,NaN
251,St. Vincent and the Grenadines,VCT,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.527283,3.694262,-6.265339,3.669726,0.884935,...,-2.099061,-3.353526,-0.419351,1.380643,1.832286,1.236505,1.367505,1.857893,NaN,NaN
252,"Venezuela, RB",VEN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.192519,8.532934,3.900951,11.129345,4.162867,...,-3.202303,-1.488791,4.176425,5.625957,1.343094,-3.894386,NaN,NaN,NaN,NaN
253,British Virgin Islands,VGB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.641493,0.904116,-8.158453,-15.019255,-5.800604,-0.962155,0.194301,NaN,NaN,NaN
255,Vietnam,VNM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.397898,6.423238,6.240303,5.247367,5.421883,5.983655,6.679289,6.210812,NaN,NaN
256,Vanuatu,VUT,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.312816,1.629082,1.223226,1.754750,1.969146,2.331006,-0.801094,4.000574,NaN,NaN
257,World,WLD,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,4.329712,5.562321,5.212080,6.663998,5.560804,...,-1.737425,4.316843,3.176860,2.446114,2.632654,2.863900,2.830909,2.487061,NaN,NaN
258,Samoa,WSM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.808272,0.479159,5.778544,0.402104,-1.933859,1.196147,1.634776,7.145169,NaN,NaN
259,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.341666,3.309575,4.619578,2.808458,3.440465,1.218534,4.076430,3.398098,NaN,NaN
260,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.866230,7.702307,-12.714897,2.392990,4.823519,-0.188690,-28.096835,-9.779168,NaN,NaN
261,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,3.844751,6.177883,7.373613,7.939782,6.122761,...,-1.538101,3.039777,3.284197,2.213259,2.489283,1.699598,1.298851,0.279357,NaN,NaN
262,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,...,9.220348,10.298206,5.564625,7.597617,5.059376,4.695826,2.919881,3.609742,NaN,NaN
263,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,6.316157,1.434471,6.244345,-1.106172,4.910571,...,12.019561,12.581027,15.445733,14.779595,5.529787,2.127084,1.689594,0.615714,NaN,NaN

In [39]:
# isolate china's GDP
china_gdp = gdp_data.loc[gdp_data["Country Name"] == "China"]
display(china_gdp)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
38,China,CHN,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,-27.27,-5.58,10.3,18.18,16.95,...,9.399813,10.63614,9.536443,7.856262,7.757635,7.297666,6.900205,6.68935,NaN,NaN

In [41]:
gdp_a = china_gdp.iloc[:,4:23]
display(gdp_a)

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978
38,NaN,-27.27,-5.58,10.3,18.18,16.95,10.65,-5.77,-4.1,16.94,19.3,7.06,3.81,7.76,2.31,8.72,-1.57,7.57,11.666644

In [42]:
gdp_b = china_gdp.iloc[:,23:len(china_gdp.columns)-2]
display(gdp_b)

,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
38,7.6,7.806691,5.172414,8.934426,10.835214,15.139172,13.443396,8.939709,11.688931,11.234515,...,14.231388,9.654289,9.399813,10.63614,9.536443,7.856262,7.757635,7.297666,6.900205,6.68935